#!/usr/bin/env bash
set -euo pipefail

AGENTS="${AGENTS_HOME:-$(cd "$(dirname "$0")/.." && pwd -P)}"

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

if rg -q \
  'TARGETS=|\.codex/AGENTS\.md|\.copilot/copilot-instructions\.md|refresh_claude_stamp|assemble_body|render_target' \
  "$AGENTS/bin/agents-sync"; then
  fail 'agents-sync still owns host global config'
fi

resolve_worktree() {
  local repo="$1" branch="$2"
  git -C "$repo" worktree list --porcelain |
    awk -v ref="refs/heads/$branch" '
      /^worktree / { path=substr($0, 10) }
      $0=="branch " ref { print path }
    '
}

CLAUDE_CANDIDATE="${CLAUDE_CANDIDATE:-$(resolve_worktree "$HOME/.claude" codex/three-host-global-config-split-claude)}"
CODEX_CANDIDATE="${CODEX_CANDIDATE:-$(resolve_worktree "$HOME/.codex" codex/three-host-global-config-split-codex)}"
COPILOT_CANDIDATE="${COPILOT_CANDIDATE:-$(resolve_worktree "$HOME/.copilot" codex/three-host-global-config-split-copilot)}"

for candidate in "$CLAUDE_CANDIDATE" "$CODEX_CANDIDATE" "$COPILOT_CANDIDATE"; do
  [ -d "$candidate" ] || fail "host candidate missing: $candidate"
done

scratch="$(mktemp -d "${TMPDIR:-/tmp}/agents-ownership.XXXXXX")"
trap 'chmod -R u+rwX "$scratch" 2>/dev/null || true; rm -rf "$scratch"' EXIT
mkdir -p "$scratch/home/.claude/skills" "$scratch/home/.codex" "$scratch/home/.copilot"

for sentinel in \
  "$scratch/home/.claude/CLAUDE.md" \
  "$scratch/home/.codex/AGENTS.md" \
  "$scratch/home/.copilot/copilot-instructions.md"; do
  printf 'host-global-config-sentinel\n' > "$sentinel"
  chmod 000 "$sentinel"
done

sentinel_before="$scratch/sentinel-before.tsv"
sentinel_after="$scratch/sentinel-after.tsv"
for sentinel in \
  "$scratch/home/.claude/CLAUDE.md" \
  "$scratch/home/.codex/AGENTS.md" \
  "$scratch/home/.copilot/copilot-instructions.md"; do
  stat -f '%N	%z	%Lp' "$sentinel" >> "$sentinel_before"
done

for mode in --check --doctor --bootstrap; do
  HOME="$scratch/home" AGENTS_HOME="$AGENTS" "$AGENTS/bin/agents-sync" "$mode" >/dev/null 2>&1 ||
    fail "skills-only mode failed: $mode"
done
for mode in default --deploy --only; do
  case "$mode" in
    default) args=() ;;
    --only) args=(--only codex) ;;
    *) args=("$mode") ;;
  esac
  if HOME="$scratch/home" AGENTS_HOME="$AGENTS" "$AGENTS/bin/agents-sync" "${args[@]}" >/dev/null 2>&1; then
    fail "retired interface did not fail loud: $mode"
  fi
done

for sentinel in \
  "$scratch/home/.claude/CLAUDE.md" \
  "$scratch/home/.codex/AGENTS.md" \
  "$scratch/home/.copilot/copilot-instructions.md"; do
  stat -f '%N	%z	%Lp' "$sentinel" >> "$sentinel_after"
done
diff -u "$sentinel_before" "$sentinel_after" >/dev/null ||
  fail 'skills-only modes changed host global config metadata'

if rg -n '\.agents/(core|rules|hooks|hosts|dist|bin)(/|`|$)' \
  "$CLAUDE_CANDIDATE/CLAUDE.md" \
  "$CLAUDE_CANDIDATE/settings.json" \
  "$CODEX_CANDIDATE/AGENTS.md" \
  "$CODEX_CANDIDATE/hooks.json" \
  "$COPILOT_CANDIDATE/copilot-instructions.md" >/dev/null; then
  fail 'active host global config still references .agents control plane'
fi

for dir in core rules hooks; do
  if find "$CLAUDE_CANDIDATE/$dir" -maxdepth 1 -type l -print -quit | grep -q .; then
    fail "Claude $dir still contains symlink"
  fi
done
for link in "$CLAUDE_CANDIDATE"/skills/*; do
  [ -L "$link" ] || fail "Claude skill is not symlink: $link"
  expected="../../.agents/skills/$(basename "$link")"
  [ "$(readlink "$link")" = "$expected" ] || fail "Claude skill target changed: $link"
done

head -1 "$CODEX_CANDIDATE/AGENTS.md" | grep -q '^<!-- GENERATED by ~/.agents/bin/agents-sync' &&
  fail 'Codex generated banner still present'
head -1 "$COPILOT_CANDIDATE/copilot-instructions.md" | grep -q '^<!-- GENERATED by ~/.agents/bin/agents-sync' &&
  fail 'Copilot generated banner still present'

for candidate in "$CODEX_CANDIDATE" "$COPILOT_CANDIDATE"; do
  for rule in cookbook cpp dotnet frontend-spa infra testing typescript winforms; do
    [ -f "$candidate/rules/$rule.md" ] || fail "local stack rule missing: $candidate/rules/$rule.md"
  done
done

if [ -s "$AGENTS/dist/manifest.tsv" ] &&
  rg -q '\.codex/AGENTS\.md|\.copilot/copilot-instructions\.md' "$AGENTS/dist/manifest.tsv"; then
  fail 'active manifest still contains host global config'
fi

skills_before="${OWNERSHIP_SKILLS_BEFORE:-/private/tmp/three-host-global-config-split-impl-skills-before.tsv}"
skills_after="${OWNERSHIP_SKILLS_AFTER:-/private/tmp/three-host-global-config-split-ownership-after.tsv}"
[ -f "$skills_before" ] || fail "ownership skills baseline missing: $skills_before"
[ -f "$skills_after" ] || fail "ownership skills after manifest missing: $skills_after"
diff -u "$skills_before" "$skills_after" >/dev/null || fail 'ownership skills manifest changed'

for carrier in \
  "$AGENTS/docs/agents/issue-tracker.md" \
  "$AGENTS/rules/typescript.md" \
  "$AGENTS/rules/frontend-spa.md"; do
  [ -f "$carrier" ] || fail "compatibility carrier missing: $carrier"
done

historical_before="${HISTORICAL_BEFORE:-/private/tmp/three-host-global-config-split-historical-before.tsv}"
historical_after="${HISTORICAL_AFTER:-/private/tmp/three-host-global-config-split-historical-after.tsv}"
[ -f "$historical_before" ] || fail "historical baseline missing: $historical_before"
[ -f "$historical_after" ] || fail "historical after manifest missing: $historical_after"
diff -u "$historical_before" "$historical_after" >/dev/null || fail 'historical artifacts changed'

live_before="${LIVE_BEFORE:-/private/tmp/three-host-global-config-split-live-before.tsv}"
live_after="${LIVE_AFTER:-/private/tmp/three-host-global-config-split-live-after.tsv}"
[ -f "$live_before" ] || fail "live baseline missing: $live_before"
[ -f "$live_after" ] || fail "live after fingerprint missing: $live_after"
diff -u "$live_before" "$live_after" >/dev/null || fail 'live repo fingerprints changed'

printf 'PASS: three-host global-config ownership contract\n'
